language: csharp
solution: SimpleDatabase.sln

install:
- nuget restore SimpleDatabase.sln
- nuget install NUnit -Version 3.12.0 -OutputDirectory testrunner
- nuget install NUnit.ConsoleRunner -Version 3.10.0 -OutputDirectory testrunner
- nuget install DeepEqual -Version 1.6.0 -OutputDirectory testrunner

script:
- msbuild /p:Configuration=Travis SimpleDatabase.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --trace=Debug --labels=All ./Test-SimpleDatabase/bin/x64/Travis/Test-SimpleDatabase.dll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./SimpleDatabase/bin/x64/Travis
  target_branch: gh-pages
  email: "github-pages-deploy@travis-ci.org"
  on:
    branch: master
